language: rust
rust: stable
os:
    - osx # Avoid too old git (1.8.5.6) on Linux worker
before_script:
    - brew install git
    - git --version
    - git checkout $TRAVIS_BRANCH # Attach git again for tests
    - git rev-parse HEAD
script:
    - cargo build
    - cargo test --verbose
notifications:
    email:
        on_success: never
        on_failure: change
