language: rust
rust: stable
before_script:
    - git checkout $TRAVIS_BRANCH # Attach git again for tests
script:
    - cargo build
    - cargo test --verbose
notifications:
    email:
        on_success: never
        on_failure: change
