[package]
name = "git-brws"
version = "0.2.0"
authors = ["rhysd <lin90162@yahoo.co.jp>"]
description = "Command line tool to open a repository, file, commit or diff in your web browser from command line"
repository = "https://github.com/rhysd/git-brws"
readme = "README.md"
include = ["src/*.rs", "Cargo.toml", "LICENSE.txt"]
license = "MIT"

[dependencies]
getopts = "0.2"
url = "1.2"
open = "1.1"
